"""added price and currency

Revision ID: 67850b982de4
Revises: eaeae262e88b
Create Date: 2026-01-17 12:19:43.797879

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '67850b982de4'
down_revision: Union[str, Sequence[str], None] = 'eaeae262e88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    currency_enum = sa.Enum('USD', 'EUR', name='currency_enum')
    currency_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('products', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('products', sa.Column('currency', currency_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'currency')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
