"""added indexes

Revision ID: 788eaa0cec70
Revises: 67850b982de4
Create Date: 2026-01-17 13:07:56.080936

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '788eaa0cec70'
down_revision: Union[str, Sequence[str], None] = '67850b982de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_stocks_available'), 'stocks', ['available'], unique=False)
    op.create_index(op.f('ix_stocks_product_id'), 'stocks', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_product_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_available'), table_name='stocks')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    # ### end Alembic commands ###
